Remove entries in the NLPModelMeta
JuliaSmoothOptimizers/AmplNLReader.jl pull request #115
Opened 2021-07-26 17:37 UTC by tmigot

Following [#372 in NLPModels.jl](https://github.com/JuliaSmoothOptimizers/NLPModels.jl/pull/372)

2021-07-26 18:53 UTC, dpo requested changes

2021-07-26 18:53 UTC, dpo commented on src/ampl_model.jl
> -      nlnet = nlnet,
Also remove the lines where those values are computed (e.g., line 98).

2021-07-26 18:53 UTC, dpo commented
Or perhaps the meta here could be somewhat more complete than the default since all those quantities are available?

2021-09-15 23:56 UTC, tmigot commented
Replaced by #116

2021-09-15 23:56 UTC, closed without merging