Add citation.cff
JuliaSmoothOptimizers/AmplNLReader.jl pull request #131
Opened 2024-01-19 21:32 UTC by tmigot

2024-01-30 08:52 UTC, abelsiqueira commented on CITATION.cff
> +    family-names: Siqueira
```suggestion
  - given-names: Abel
    family-names: Soares Siqueira
```

2024-01-30 08:53 UTC, abelsiqueira commented on CITATION.cff
> +commit: 15165b0086abe9dd05b0ba34b3076ee5e20cb156
```suggestion
```
I would remove this. We have a DOI, a version and a date-released, so it is more than sufficient.

2024-01-30 08:54 UTC, abelsiqueira commented on CITATION.cff
> +      Polytechnique       Montréal,             QC, Canada
Were these extra spaces added automatically by cffinit?

2024-01-30 08:54 UTC, abelsiqueira requested changes
I've made some comments, thanks for the work.

2024-02-02 22:10 UTC, tmigot commented on CITATION.cff
> +      Polytechnique       Montréal,             QC, Canada
Oh no, it is just a copy paste from somewhere else

2024-02-02 22:13 UTC, tmigot commented on CITATION.cff
> +      Polytechnique       Montréal,             QC, Canada
```suggestion
    affiliation: 'GERAD and Department of Mathematics and Industrial Engineering, Polytechnique Montréal, QC, Canada'
```

2024-02-04 15:46 UTC, merged